all:
  hosts:
    web01:
      ansible_host: 172.31.41.84
      ansible_user: ec2-user
      ansible_ssh_private_key_file: webkey.pem
    web02:
      ansible_host: 172.31.44.203
      ansible_user: ec2-user
      ansible_ssh_private_key_file: webkey.pem
    db01:
      ansible_host: 172.31.32.60
      ansible_user: ec2-user
      ansible_ssh_private_key_file: webkey.pem
  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    dc_oregon:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: webkey.pem
