---
- name: Provisioning servers
  hosts: all
  become: yes
  tasks:
    - name: Install NTP agent on CentOS
      yum:
        name: "{{ item }}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - chrony
        - wget
        - git
        - zip
        - unzip

    - name: Install NTP agent on Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name: Start service on CentOS
      service:
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start service on Ubuntu
      service:
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"






#output


 ansible-playbook -i inventory pro.yaml

PLAY [Provisioning servers] ********************************************************************

TASK [Gathering Facts] *************************************************************************
ok: [web01]
ok: [db01]
ok: [web02]
ok: [web03]

TASK [Install NTP agent on CentOS] *************************************************************
skipping: [web03] => (item=chrony)
skipping: [web03] => (item=wget)
skipping: [web03] => (item=git)
skipping: [web03] => (item=zip)
skipping: [web03] => (item=unzip)
skipping: [web03]
ok: [web01] => (item=chrony)
ok: [web02] => (item=chrony)
ok: [db01] => (item=chrony)
ok: [web01] => (item=wget)
ok: [db01] => (item=wget)
ok: [web02] => (item=wget)
ok: [web01] => (item=git)
ok: [db01] => (item=git)
ok: [web02] => (item=git)
ok: [web01] => (item=zip)
ok: [db01] => (item=zip)
ok: [web02] => (item=zip)
ok: [web01] => (item=unzip)
ok: [db01] => (item=unzip)
ok: [web02] => (item=unzip)

TASK [Install NTP agent on Ubuntu] *************************************************************
skipping: [web01] => (item=ntp)
skipping: [web01] => (item=wget)
skipping: [web01] => (item=git)
skipping: [web01] => (item=zip)
skipping: [web01] => (item=unzip)
skipping: [web02] => (item=ntp)
skipping: [web02] => (item=wget)
skipping: [web02] => (item=git)
skipping: [web02] => (item=zip)
skipping: [web01]
skipping: [web02] => (item=unzip)
skipping: [web02]
skipping: [db01] => (item=ntp)
skipping: [db01] => (item=wget)
skipping: [db01] => (item=git)
skipping: [db01] => (item=zip)
skipping: [db01] => (item=unzip)
skipping: [db01]
ok: [web03] => (item=ntp)
ok: [web03] => (item=wget)
ok: [web03] => (item=git)
ok: [web03] => (item=zip)
ok: [web03] => (item=unzip)

TASK [Start service on CentOS] *****************************************************************
skipping: [web03]
ok: [web01]
ok: [db01]
ok: [web02]

TASK [Start service on Ubuntu] *****************************************************************
skipping: [web01]
skipping: [web02]
skipping: [db01]
ok: [web03]

TASK [Banner] **********************************************************************************
ok: [web03]
ok: [web01]
ok: [db01]
ok: [web02]

TASK [Create chrony directory on CentOS] *******************************************************
skipping: [web03]
changed: [web01]
changed: [web02]
changed: [db01]

TASK [Deploy ntp agent conf on CentOS] *********************************************************
skipping: [web03]
ok: [web01]
ok: [web02]
ok: [db01]

TASK [Deploy ntp agent conf on Ubuntu] *********************************************************
skipping: [web01]
skipping: [web02]
skipping: [db01]
ok: [web03]

TASK [Restart service on CentOS] ***************************************************************
skipping: [web03]
changed: [web01]
changed: [web02]
changed: [db01]

TASK [Restart service on Ubuntu] ***************************************************************
skipping: [web01]
skipping: [web02]
skipping: [db01]
changed: [web03]

PLAY RECAP *************************************************************************************
db01                       : ok=7    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
web01                      : ok=7    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
web02                      : ok=7    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
web03                      : ok=6    changed=1    unreachable=0    failed=0    skipped=5    rescued=0    ignored=0



todo

centos
    1  cat /etc/chrony.conf
    2  history

ubuntu

  
    5  cat /etc/ntp/ntp.conf
    6  cat /etc/ntp
    8  cat /etc/ntp.conf

paste that in control machine

~/profile/exercise4# cd templates/
root@ip:~/profile/exercise4/templates# ls
ntpconf_centos  ntpconf_ubuntu

pool 2.centos.pool.ntp.org iburst


get network time protocol from web
USRNM: commonuser
COMM: Variable from groupvars_all fie
ntp0: 0.north-america.pool.ntp.org
ntp1: 1.north-america.pool.ntp.org
ntp2: 2.north-america.pool.ntp.org
ntp3: 3.north-america.pool.ntp.org


add in group_vars/all

add this in both config files 

pool "{{ntp0}}" iburst
pool "{{ntp1}}" iburst
pool "{{ntp2}}" iburst
pool "{{ntp3}}" iburst
